export const themes = [
  "light",
  "dark",
  "dracula",
  "solarpunk",
  "nord",
  "grand-line",
  "starship-hud",
  "matcha-latte",
  "cyberpunk",
  "retro",
  "canyon-glow",
  "ocean",
  "monokai",
  "shinobi-sunset",
  "twilight-indigo",
  "lumora",
  "art-deco",
  "lavender",
  "midnight",
  "sunset",
  "espresso",
  "barbie",
  "blueprint",
  "vscode",
  "old-manuscript",
  "noctis",
  "pixel-arcade",
  "brutalism",
  "doom-64",
  "forest",
  "aurora-dusk",
  "desert-glass",
  "zen-mist",
  "cloudbound",
  "pebble-shore",
  "lavender-fields",
  "sunset-bistro",
  "serene-tropic",
  "industrial-dawn",
  "nordic-orchard"
] as const

export type Theme = (typeof themes)[number]